version: '3.7'
services:
  postgresql:
    image: repository.dimas-maryanto.com:8086/postgres:12.1
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=hr
      - POSTGRES_USER=hr
      - POSTGRES_DB=hr
  flyway: 
    image: boxfuse/flyway
    command: -url=jdbc:postgresql://postgresql:5432/bootcamp -schemas=hr -user=hr -password=hr -connectRetries=60 migrate
    volumes:
      - ./schema:/flyway/sql
    depends_on:
      - postgresql
volumes:
  pg_data:
